applicationame: Kalman
simulation:
  scansPerSecond: 10
  steps: 50
target:
  minDistance: 50.0
  maxDistance: 50.0
  minVelocity: 10.0
  maxVelocity: 20.0
  minAcceleration: 0.0
  maxAcceleration: 0.0
sensors:
  - name: GPS
    type: global
    stdX: 1.0 # Unit: meters
    stdY: 1.0 # Unit: meters
    correlation: 0.0 # between -1 and 1
    missChance: 0.01
    missLength: 5
  # - name: dGPS
  #   type: global
  #   stdX: 1.0 # Unit: meters
  #   stdY: 1.0 # Unit: meters
  #   correlation: 0.0 # between -1 and 1
  #   missChance: 0.25
  #   missLength: 10


